### ISSUE TITLE
BigQClient/ServerTest not connecting

### ISSUE THREAD

**Issue by LostSoulFly** [bigqio/bigq#2]
The test projects don't seem to be working:
![image](https://cloud.githubusercontent.com/assets/9120519/21035387/a41b6076-bd8c-11e6-9a60-427cc77e9a48.png)

Your other Chat project on GitHub seems to work fine, however.

**Comment by jchristn** [comment]
Thank you for letting me know, I moved the server it is dependent on and
forgot to restart the test server. I will do that as soon as I get home
tonight!

On Dec 8, 2016 18:24, "LostSoulFly" <notifications@github.com> wrote:

The test projects don't seem to be working:
[image: image]
<https://cloud.githubusercontent.com/assets/9120519/21035387/a41b6076-bd8c-11e6-9a60-427cc77e9a48.png>

Your other Chat project on GitHub seems to work fine, however.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bigqio/bigq/issues/2>, or mute the thread

**Comment by jchristn** [comment]
There is a bug in how I'm determining if the socket is connected.  I'm fixing it now but will have to change some of the surrounding code.  Sorry for the delay.

**Comment by LostSoulFly** [comment]
No worries! I'm just glad it wasn't on my end! :-)

**Comment by jchristn** [comment]
Hi LostSoulFly, it appears my check for client disconnection was unreliable and that was hanging up the data receiver loop on the server side for the client test project.  I've put in a temporary rework to force use of heartbeats and moved the disconnect detection into the heartbeat logic.  The upside is that it should always detect disconnect reliably now.  The problem with TCP is that I can't reliably detect disconnect immediately without using heartbeats, so there is a window of time between where a client forcibly disconnects and the server detects it and removes the client from its internal state (this is common for most TCP socket apps).

I'm thankful that you raised this issue.  It also pointed out a larger refactor and simplification effort that I need to put in, and plan to do so over the coming week which should make the code a lot easier.  I'll be updating NuGet as well after the refactor.

Going to close this issue; please let me know if you encounter more!

**Comment by LostSoulFly** [comment]
Surely there's a way to more expediently and reliably detect disconnects?

I'm very much still learning C# but I seem to recall it being quite fast and reliable back in my days of VB6 with Winsock.

Without the ability to detect disconnects quickly, won't that pose a problem for reliable message distribution? How does bigq handle a scenario where a message was supposed to be delivered? Is that something that I'd have to implement?

**Comment by jchristn** [comment]
Hi LostSoulFly, there are several mechanisms but you'll find from Stephen Cleary's blog that the best mechanism is to use an application-layer heartbeat (see http://blog.stephencleary.com/2009/04/tcpip-net-sockets-faq.html).  For messages that failed delivery.  For now, while I work on persistence, the best options are to either use synchronous messaging (which does kind of defeat the purpose IMO) or rely on server/channel join/leave notifications.  Like with any MQ I'd recommend that an app-layer mechanism for acknowledgement be built in.  BigQ can certainly send message sent acknowledgements to the sender but we can't guarantee that the receiver does anything with it (or that the socket is responsive - again per Stephen's blog).  Hope this helps!

**Comment by LostSoulFly** [comment]
That makes sense.

I had another question. I've not successfully been able to create a client/server without loading a config (or using a null/default). Is there a reason it can't be programmatically initialized to a specific IP/port? Or am I missing something completely obvious?

**Comment by jchristn** [comment]
Hi LostSoulFly, that's very weird, it should work.  What is the issue you are encountering?  If it helps, I can add another constructor that takes an IP/port as input - let me know!

**Comment by LostSoulFly** [comment]
Sorry for the late reply. I'm probably not initializing it properly. Could
I trouble you for a quick example?

**Comment by jchristn** [comment]
Yes of course!
