### ISSUE TITLE
could I use html5 to connect  biggio server?

### ISSUE THREAD

**Issue by johnhuang669** [bigqio/bigq#3]
could I use html5 to connect  biggio server?

how to do that? to subscribe ,to join channel....

**Comment by jchristn** [comment]
Hi @johnhuang669 using HTML5 and Javascript you can certainly connect to a bigq server.  If you check [here](https://github.com/bigqio/chat-js/blob/master/bigq-js-chat.js) you'll see a chat client built using Javascript.  I don't have an SDK yet for Javascript but that is doable.

**Comment by johnhuang669** [comment]
is that node js ??
and I don't know how to subscribe ,,to join channel  in the sample that you mean....

**Comment by jchristn** [comment]
Hi @johnhuang669 yes indeed.  You're correct, I don't have a channel example in there.  I'll work on getting a proper Javascript SDK including channel support over the weekend, rather than a self-contained program (which is what the link is).  Thanks!

**Comment by jchristn** [comment]
Hi @johnhuang669 the JS client end is proving to be a bit more than I'm willing to take on.  I'm happy to provide you the message samples with framing to support channels if you'd like to give it a go.  Just re-open and let me know!  Thanks

**Comment by jchristn** [comment]
Re-opening this, I think I might have found a solution to a blocker that made me give up hope :)

**Comment by jchristn** [comment]
Hi @johnhuang669 I haven't forgotten about this, working on a proper SDK for Javascript.  Will take me a bit more time.

**Comment by johnhuang669** [comment]
ok , thank your help !!

**Comment by jchristn** [comment]
HI @johnhuang669  you can see progress here: https://github.com/bigqio/sdk-js  I have a long way to go, but ideally we'll be able to handle both channel and direct messaging with this.  It's not anywhere near ready yet but wanted you to see progress.  If you have any feedback please let me know.  Also eventually I'd like to be able to allow the caller to tie callbacks to events so they don't have to handle messages on their end.

**Comment by jchristn** [comment]
Hi @johnhuang669 this is a little early but I've been able to run a series of successful tests.  I'd love your feedback: https://github.com/bigqio/sdk-js  I'll close the issue here - if you have any feedback on issues or enhancements please do open another issue on the ```sdk-js``` repo.  Thanks!
