### ISSUE TITLE
how do I clear the close connection in WebsocketServer?

### ISSUE THREAD

**Issue by johnhuang669** [bigqio/bigq#4]
Sir,

I have a problem. while the client close the browser, the connection still exist in the WebsocketServer.
how do I to detect the useless connections?

**Comment by jchristn** [comment]
Hi @johnhuang669 - the server will automatically detect that the client is no longer connected when heartbeats begin failing.  Here is my console output showing the behavior.  I connected with the JS client, listed the clients, and then disconnected.  The server detected the disconnection.

```
D:\Code\BigQ\BigQ\BigQServerTest\bin\Debug>bigqservertest --cfg=server.json

BigQ Server Version 1.7.4.0

Attempting to start/restart server using server.json
Command [? for help]:
 | Message ID 866519e1-9ace-2837-aa50-405002a10a09 Created 06/15/2017 15:31:30.0000000
 | default -> 00000000-0000-0000-0000-000000000000
 | Email default Command Login Content Type application/octet-stream SyncRequest False
 | Data: (null)

ClientConnected received notice of client login GUID default from 127.0.0.1:64104

 | Message ID 815c31dd-99ec-551c-32a8-ce16b4c08ccc Created 06/15/2017 15:31:39.0000000
 | default -> 00000000-0000-0000-0000-000000000000
 | Email default Command ListClients Content Type application/octet-stream SyncRequest False
 | Data: (null)

06/15/2017 15:31:59 Warn DESKTOP-JVA27P9 thr-10       HeartbeatManager maximum number of failed heartbeats reached, abandoning client 127.0.0.1:64104
06/15/2017 15:31:59 Warn DESKTOP-JVA27P9 thr-10        ServerLeaveEvent no clients found on server
```

**Comment by johnhuang669** [comment]
Heartbeat is  demo data??

**Comment by jchristn** [comment]
Hi @johnhuang669 heartbeat is on my default, contains null data, and is only used to detect if the connection is still open.  Is it working for you now?  Cheers!

**Comment by jchristn** [comment]
See line 1016: https://github.com/bigqio/bigq/blob/master/BigQ/Server.cs

**Comment by johnhuang669** [comment]
yes,it' working for me now!

I have to test how many clients connect to the server will cause crash...

**Comment by jchristn** [comment]
Awesome, glad it's working @johnhuang669 - thanks for letting me know :)  Closing this one.
