### ISSUE TITLE
webscoket SSL

### ISSUE THREAD

**Issue by johnhuang669** [bigqio/bigq#5]
sir,

I can't use the test.pfx to connect webscoket server by  SSL

show: RR_CERT_COMMON_NAME_INVALID

**Comment by jchristn** [comment]
Hi @johnhuang669 is there exception output on the console that you can share?  You might have to generate one from your own machine since it's a self-signed certificate - your machine might not like mine.  Cheers

**Comment by johnhuang669** [comment]
sir,
it's no exception on server side.
how to generate self-signed certificate to test ??

**Comment by jchristn** [comment]
Hi @johnhuang669 - here are two ways to do it.  The first is using IIS, the second is with makecert.exe.  Once you have the PFX file, be sure to import it into the Personal certificate store for the Computer account using the MMC (start -> run -> mmc -> Add Snap-In -> Certificates).  You may also have to add it to the Personal certificate store for the current user account.

1) Using IIS: https://technet.microsoft.com/en-us/library/cc753127(v=ws.10).aspx
2) Using makecert: https://blog.jayway.com/2014/09/03/creating-self-signed-certificates-with-makecert-exe-for-development/

Cheers
Joel

**Comment by jchristn** [comment]
Hi @johnhuang669 let me know if this resolved the issue for you.  Cheers!

**Comment by johnhuang669** [comment]
sir,
first , I have to study how to generate the certificate to test.....

**Comment by jchristn** [comment]
Thanks John, sorry, wasn't trying to rush you.  Another thing to do is, if you create a self-signed certificate, be sure to set the AcceptInvalidCerts flag in the JSON config file to true.  Otherwise the cert will never get validated.

**Comment by johnhuang669** [comment]
Sir,

Why do I have to set the config item AcceptInvalidCerts to true??

AcceptInvalidCerts is mean not to validate the certificate whatever it is true or false?

So if I have the the real certificate, the acceptinvalidcert has to set false?

**Comment by jchristn** [comment]
Hi @johnhuang669 - if it's a self-signed certificate that you created on your own machine, then yes you should set AcceptInvalidCerts to true.  If you set it to false, it will attempt to be validated with a CA for trustworthiness.  CAs on the Internet won't know about your self-signed cert and it will thus be declined and the connection will fail.

**Comment by jchristn** [comment]
Hi @johnhuang669 any chance you were able to give this a go?  Please feel free to re-open this one if you are still having issues!

**Comment by johnhuang669** [comment]
sir,

Can it's show the video on the web page by websocket?

could you give me the sample code

thanks

**Comment by jchristn** [comment]
Hi @johnhuang669  are you asking if Websockets can be used to stream video from a server to client?  If so then yes, Websockets are just a transport.  There would need to be a file handle on the server side reading the content from the source and writing it to the websocket, and some kind of client reading and displaying.  I wouldn't have the sample code for that (it would be outside of bigq) but you might want to look into something like this: http://weheart.digital/build-simple-live-streaming-solution/  Cheers
