### ISSUE TITLE
Error when deserializing the list of clients

### ISSUE THREAD

**Issue by mpenna** [bigqio/bigq#6]
Not sure if it's some lack of configuration or what, but I'm getting a deserialization exception when pulling the list of clients by issuing the "listclients" command from a connected client. This is happening while running the ServerTest and ClientTest sample apps. 

Newtonsoft.Json.JsonSerializationException: 'Cannot create and populate list type System.Collections.Concurrent.BlockingCollection`1[BigQ.Core.Message]. Path '[0].MessageQueue'.'

Apparently something to do with Json.Net not being able to deserialize the MessageQueue property into a BlockingCollection.

**Comment by jchristn** [comment]
Hi @mpenna great catch, thank you.  Yes, I need to decorate with a JSON ignore in there.  I will be sure to get this in tonight!  Thanks again

**Comment by jchristn** [comment]
Hi @mpenna I just pushed a commit with this in the Core library and it should be working.  I have a handful of items on my list to do with this project in the next week so I'll also likely be making some of those members private/internal.  Thanks for letting me know and please confirm this resolves the issue so I can close it.  Cheers

**Comment by mpenna** [comment]
Great! That indeed fixed it, thanks. Hey, great library, by the way. 

I know we should stick these discussions to the issue's main topic, but going through the ServerTest code, I couldn't help noticing but it looks like a section of code inside the StartServer() function has been inadvertently duplicated: 

```C#
        static bool StartServer()
        {
            Console.WriteLine("Attempting to start server");

            if (server != null) server.Dispose();
            server = null;
              
            config = ServerConfiguration.Default();
            config.TcpServer.Debug = true;

            server = new Server(config);
            server.Callbacks.MessageReceived = MessageReceived;
            server.Callbacks.ServerStopped = StartServer;
            server.Callbacks.ClientConnected = ClientConnected;
            server.Callbacks.ClientLogin = ClientLogin;
            server.Callbacks.ClientDisconnected = ClientDisconnected;
            
            server.Callbacks.MessageReceived = MessageReceived;
            server.Callbacks.ServerStopped = StartServer;
            server.Callbacks.ClientConnected = ClientConnected;
            server.Callbacks.ClientLogin = ClientLogin;
            server.Callbacks.ClientDisconnected = ClientDisconnected;

            return true;
        }
```

**Comment by jchristn** [comment]
Hi @mpenna indeed it was.  Thanks for pointing that out.  I had noticed that last night when I was doing some cleanup on the library.  I'll be making some minor changes (though there will be breaking changes) and publishing an update this week.  Glad you're enjoying the library and definitely looking forward to any other issues or feedback!  Cheers!

**Comment by jchristn** [comment]
Closing this one, both the deserialization and the duplicate code issues will be in the next commit.  Thanks again!
